// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnuzwrlgjtuqoiadsnhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJudXp3cmxnanR1cW9pYWRzbmhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MjI5ODQsImV4cCI6MjA1MjA5ODk4NH0.WQdNPaO-oSEfymsEPJ2mbLU6nO0IXhEQqKRq708t8G8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);